name: Monitoring Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # runs every 6 hours

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout monitoring repo (this repo)
      - name: Checkout monitoring repo
        uses: actions/checkout@v4

      # 2️⃣ Checkout Terraform repo (Tf-den)
      - name: Checkout Terraform repo
        uses: actions/checkout@v4
        with:
          repository: Dency-28/Tf-den
          path: Tf-den

      # 3️⃣ Set up SSH key for EC2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYER_NEW }}" > ~/.ssh/deployer.pem
          chmod 600 ~/.ssh/deployer.pem

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible curl jq unzip

      # 5️⃣ Update inventory from Terraform output
      - name: Update Ansible Inventory
        run: bash Scripts/update_inventory.sh

      # 6️⃣ Run Ansible monitoring playbook
      - name: Run Monitoring Playbook
        run: ansible-playbook -i inventory.ini Playbooks/monitoring.yml

      # 7️⃣ Run Health Check Script
      - name: Run Health Check
        run: bash Scripts/check_health.sh
